name: E-KTA Deploy

permissions:
  contents: write
  
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/5 * * * *" 
  workflow_dispatch:
  
jobs:

  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/alvinsdrive2-stack/KTA.git || true
          git fetch upstream

      - name: Check for changes
        id: diff
        run: |
          git fetch upstream

          NEW=$(git rev-list master..upstream/master --count)
      
          echo "new=$NEW"
      
          if [ "$NEW" -eq 0 ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Set Git identity
        run: |
          git config --global user.name "gatensigapensi-svg"
          git config --global user.email "gatensigapensi@gmail.com"

      - name: Merge upstream
        if: steps.diff.outputs.changed == 'true'
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories --no-edit -- . ":(exclude).github/workflows"
          git push origin master

      - name: Deploy to server
        if: steps.diff.outputs.changed == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

          rsync -avz -e "ssh -p ${{ secrets.DEPLOY_PORT }}" \
            --exclude=".git" \
            $GITHUB_WORKSPACE/ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}

          ssh -p ${{ secrets.DEPLOY_PORT }} \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "cd ${{ secrets.DEPLOY_PATH }} && npm ci && npm run build && pm2 restart ekta-dummy"
